version: '3.9'
services:
  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sample
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
